name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-tests.txt
    - name: Run tests
      working-directory: tests
      env:
        RESTAURANT_TABLE: fake_test_table
        AWS_DEFAULT_REGION: us-east-1
      run: |
        pytest test_lambda_handler.py
